name: CD Dev

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches: [ main ]
    types:
      - opened
      - synchronize
      - closed
  workflow_dispatch:

jobs:
  DeployEuDev:
    name: Deploy to eu-central-1/test
    runs-on: ubuntu-latest
    needs: [Build]
    if: |
      (startsWith(github.ref, 'refs/heads/feature/') && github.event_name == 'push') ||
      (github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize'))
    steps:
      - name: Deploy
        run: echo I am deploying to Dev!
