name: CI/CD Pipeline

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - name: Build Step
        run: echo "Building..."

  deployDevelop:
    name: Deploy to Develop
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - name: Deploy to Develop Step
        run: echo "Deploying to Develop..."

  deployStage:
    name: Deploy to Stage
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Deploy to Stage Step
        run: echo "Deploying to Stage..."

  deployProduction:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Deploy to Production Step
        run: echo "Deploying to Production..."
