name: CI + CD

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches: [ main ]
    types:
      - opened
      - synchronize
      - closed
  workflow_run:
    workflows: ["CI + CD"]
    types:
      - completed

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: echo Hello, world!

  DeployDev:
    name: Deploy to Dev 
    runs-on: ubuntu-latest
    needs: [Build]
    if: startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - name: Deploy
        run: echo I am deploying to Dev!

  DeployStaging:
    name: Deploy to Staging 
    runs-on: ubuntu-latest
    needs: [Build]
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
    environment: 
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying to Staging!

  DeployProd:
    name: Deploy to Production 
    runs-on: ubuntu-latest
    needs: [DeployStaging]
    if: >
      github.event_name == 'workflow_run' &&
      github.event.workflow == 'CI + CD' &&
      github.event.conclusion == 'success'
    environment: 
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying to Production!
