name: CI + CD

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches: [ main ]
    types:
      - opened
      - synchronize
      - closed
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: echo Hello, world!

  DeployDev:
    name: Deploy to Dev 
    runs-on: ubuntu-latest
    needs: [Build]
    if: startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - name: Deploy
        run: echo I am deploying to Dev!

  DeployStaging:
    name: Deploy to Staging 
    runs-on: ubuntu-latest
    needs: [Build]
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
    environment: 
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying to Staging!

  DeployProdTrigger:
    name: Trigger DeployProd
    runs-on: ubuntu-latest
    needs: [DeployStaging]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Trigger DeployProd
        run: echo "DeployProd Triggered"

  DeployProd:
    name: Deploy to Production 
    runs-on: ubuntu-latest
    needs: [DeployProdTrigger]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event.pull_request.merged == true
    environment: 
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying to Production!
