name: Develop Tag

on:
  pull_request:
    branches: [ develop ]
    types:
      - opened
      - synchronize
      - closed
  workflow_dispatch:
jobs:
  # criar a tag na develop se o a pr for concluida
  TagEuDev: 
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && 
            github.event.action == 'closed' && 
            github.event.pull_request.merged == true && 
            github.event.pull_request.base.ref == 'develop' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Latest Tag
        id: latest_tag
        run: echo ::set-output name=TAG_VERSION::$(git describe --tags --abbrev=0)

      - name: Determine Next Version
        id: next_version
        run: |
          TAG_VERSION=$(echo "${{ steps.latest_tag.outputs.TAG_VERSION }}" | awk -F. -v OFS=. '{$NF = $NF + 1;} 1')
          echo ::set-output name=TAG_VERSION::${TAG_VERSION}

      - name: Create Tag
        run: |
          echo "Creating tag v${{ steps.next_version.outputs.TAG_VERSION }}"
          git tag -a "v${{ steps.next_version.outputs.TAG_VERSION }}" -m "Tagging version ${{ steps.next_version.outputs.TAG_VERSION }}"
          git push origin "v${{ steps.next_version.outputs.TAG_VERSION }}"