name: Develop Tag

on:
  pull_request:
    branches: [ develop ]
    types:
      - opened
      - synchronize
      - closed
  workflow_dispatch:
jobs:
  # criar a tag na develop se o a pr for concluida
  TagEuDev: 
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && 
            github.event.action == 'closed' && 
            github.event.pull_request.merged == true && 
            github.event.pull_request.base.ref == 'develop' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git Identity
        run: |
          git config user.email "eduardo.gobetti@gmail.com"
          git config user.name "Eduardo Gobetti"

      - name: Pull latest changes
        run: git pull

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false