name: Primeira Action

on:
  push:
    branches:
      - main

jobs:
  primeiro_job:
    name: Executar Primeira Action
    runs-on: ubuntu-latest
    steps:
      - name: Primeira Etapa
        run: echo "Executando Primeira Action"

  job_sem_dependencia:
    name: Job Sem Dependência
    runs-on: ubuntu-latest
    steps:
      - name: Etapa Sem Dependência
        run: echo "Executando Job Sem Dependência"
